context:
  name: gxrio
  version: "1.0.2"

package:
  name: libgxrio
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 639b19a6aaf2f1f576a620c120e7dc5dd392eb2cdc3d75cc677c1d7aca2502bf

build:
  number: 4

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - ${{ "jom" if win else "make" }}
    - cmake
  host:
    - libboost-devel
    - liblzma
    - zlib
  ignore_run_exports:
    from_package:
      - libboost-devel

tests:
  - package_contents:
      include:
        - gxrio.hpp

about:
  homepage: https://forge.hekkelman.net/maarten/gxrio
  repository: https://forge.hekkelman.net/maarten/gxrio
  documentation: https://forge.hekkelman.net/maarten/gxrio/src/tag/v${{ version }}/README.md
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: "A header only library to read and write compressed files using a standard streams interface"

extra:
  recipe-maintainers:
    - eunos-1128
