context:
  name: gxrio
  version: "1.2.0"

package:
  name: libgxrio
  version: ${{ version }}

source:
  url: https://forge.hekkelman.net/maarten/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: b70839c405cc56f11f4d8e236ff12be09f350f2ac44ab876193fe342f7c68c8e

build:
  number: 0

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - ${{ "jom" if win else "make" }}
    - cmake
  host:
    - catch2
    - libboost-devel
    - liblzma-devel
    - zlib
  ignore_run_exports:
    from_package:
      - catch2
      - libboost-devel

tests:
  - package_contents:
      include:
        - gxrio.hpp

about:
  homepage: https://forge.hekkelman.net/maarten/gxrio
  repository: https://forge.hekkelman.net/maarten/gxrio
  documentation: https://forge.hekkelman.net/maarten/gxrio/src/tag/v${{ version }}/README.md
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: "A header only library to read and write compressed files using a standard streams interface"

extra:
  recipe-maintainers:
    - eunos-1128
